<div id="welcome">
    <h1>Welcome</h1>
    <?php
    echo "<ul>";
    echo "<li><a href='";
    echo $this->url(array('controller' => 'index', 'action' => 'searchshows'));
    echo "' >Search for shows</a></li>";
    $authenticationdata = Zend_Auth::getInstance();
    if (!$authenticationdata->hasIdentity()) {
        echo "<li><a href='";
        echo $this->url(array('controller' => 'index', 'action' => 'login'));
        echo "' >Staff login</a></li>";
    } else {
        echo "<li><a href='";
        echo $this->url(array('controller' => 'index', 'action' => 'scheduleevent'));
        echo "' >Schedule event</a></li>";
        echo "<li><a href='";
        echo $this->url(array('controller' => 'index', 'action' => 'addinfo'));
        echo "' >Add information to event record</a></li>";
    }
    echo "</ul>";
    ?>
</div>