<?php

if ($this->report) {
    echo '<h1>Data submitted in form</h1>';
    echo "<h2>Title</h2>";
    $title = $this->report['title'];
    echo "<p>$title</p>";
        echo "<h2>Other data</h2>";
    $color = $this->report['color'];
    echo "<p>Your chosen color code $color</p>";
    $date1 = $this->report['date1'];
    $date2 = $this->report['date2'];
    
    echo "<p>Start date $date1 and end date $date2</p>";
    
    $url = $this->report['url'];
    echo "<p>A URL $url</p>";
    
    $email = $this->report['email'];
    echo "<p>Email $email</p>";
    
    $numb = $this->report['numb'];
    $range = $this->report['range'];
    
    echo "<p>Number $numb and range value $range</p>";
    
    
    
} else {

    echo "<h1 align='center'>Create new show record</h1>";
    echo $this->form;
}