<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Entertainment Centre');
$this->headLink()->appendStylesheet($this->baseUrl() . '/css/mystyles.css');
//$this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js');
$this->headScript()->appendFile($this->baseUrl() . '/js/demo.js');

echo $this->doctype();
?>
<html >
    <head>
        <?php
        echo $this->headMeta(),
        $this->headTitle(), $this->headScript(), $this->headLink();
        ?>

    </head>

    <!--    <body onload='sayhello();'>-->
    <body >
        <div id='headdiv'>
            <img src="<?php echo $this->baseUrl() . '/siteimages/logo.jpg'; ?>" />
            <div id="ident"><p>Entertainment Centre</p></div>
        </div>
        <?php
        $authenticationdata = Zend_Auth::getInstance();
        if ($authenticationdata->hasIdentity()) {
            echo "<div id='loggedin'>";
            echo "<h2>Logged in</h2>";
            echo "<p>Currently logged in as ";
            echo $authenticationdata->getIdentity()->fullname;
            echo "; role = ";
            echo $authenticationdata->getIdentity()->role;
            echo ". <a href='";
            echo $this->url(array('controller' => 'index', 'action' => 'logout'));
            echo "' >Logout</a></p>";
            echo "</div>";
        }
        ?>
        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>
    </div>

</body>
</html>